apiVersion: v1
kind: Secret
metadata:
  name: git-credential
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://ValberJunior@bitbucket.org/valberjunior/jornadaspring.git
  username: not-used
  password: XJ74MdGtrXzcZ4x5bXFr